### ISSUE TITLE
psycopg2.errors.NumericValueOutOfRange

### ISSUE THREAD

**Issue by markusressel** [markusressel/DeineMudda#64]
```
  | 2021-03-01 22:54:55 | (Background on this error at: http://sqlalche.me/e/9h9h)
-- | -- | --
  | 2021-03-01 22:54:55 | [parameters: {'id': -10010317*****, 'type': 'supergroup'}]
  | 2021-03-01 22:54:55 | [SQL: INSERT INTO chats (id, type) VALUES (%(id)s, %(type)s)]
  | 2021-03-01 22:54:55 |  
  | 2021-03-01 22:54:55 | sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range
  | 2021-03-01 22:54:55 | cursor.execute(statement, parameters)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
  | 2021-03-01 22:54:55 | cursor, statement, parameters, context
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
  | 2021-03-01 22:54:55 | raise exception
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
  | 2021-03-01 22:54:55 | sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
  | 2021-03-01 22:54:55 | e, statement, parameters, cursor, context
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
  | 2021-03-01 22:54:55 | distilled_params,
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
  | 2021-03-01 22:54:55 | return connection._execute_clauseelement(self, multiparams, params)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
  | 2021-03-01 22:54:55 | return meth(self, multiparams, params)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
  | 2021-03-01 22:54:55 | c = cached_connections[connection].execute(statement, multiparams)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1083, in _emit_insert_statements
  | 2021-03-01 22:54:55 | insert,
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
  | 2021-03-01 22:54:55 | uow,
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
  | 2021-03-01 22:54:55 | rec.execute(self)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
  | 2021-03-01 22:54:55 | flush_context.execute()
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
  | 2021-03-01 22:54:55 | raise exception
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
  | 2021-03-01 22:54:55 | exc_value, with_traceback=exc_tb,
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
  | 2021-03-01 22:54:55 | transaction.rollback(_capture_exception=True)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
  | 2021-03-01 22:54:55 | self._flush(objects)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
  | 2021-03-01 22:54:55 | self.session.flush()
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
  | 2021-03-01 22:54:55 | self._prepare_impl()
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
  | 2021-03-01 22:54:55 | self.transaction.commit()
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
  | 2021-03-01 22:54:55 | session.commit()
  | 2021-03-01 22:54:55 | File "/app/deinemudda/persistence/__init__.py", line 62, in _session_scope
  | 2021-03-01 22:54:55 | next(self.gen)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
  | 2021-03-01 22:54:55 | session.merge(chat)
  | 2021-03-01 22:54:55 | File "/app/deinemudda/persistence/__init__.py", line 75, in add_or_update_chat
  | 2021-03-01 22:54:55 | self._persistence.add_or_update_chat(chat)
  | 2021-03-01 22:54:55 | File "/app/deinemudda/bot.py", line 170, in _any_message_callback
  | 2021-03-01 22:54:55 | return self.callback(update, context)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/telegram/ext/handler.py", line 117, in handle_update
  | 2021-03-01 22:54:55 | handler.handle_update(update, self, check, context)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 390, in process_update
  | 2021-03-01 22:54:55 | Traceback (most recent call last):
  | 2021-03-01 22:54:55 |  
  | 2021-03-01 22:54:55 | The above exception was the direct cause of the following exception:
  | 2021-03-01 22:54:55 |  
  | 2021-03-01 22:54:55 |  
  | 2021-03-01 22:54:55 | psycopg2.errors.NumericValueOutOfRange: integer out of range
  | 2021-03-01 22:54:55 | cursor.execute(statement, parameters)
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
  | 2021-03-01 22:54:55 | cursor, statement, parameters, context
  | 2021-03-01 22:54:55 | File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
```

**Comment by markusressel** [comment]
fixed in 12c6cdfa
